openapi: 3.0.3
info:
  title: Webform Feedback API
  description: API for collecting and exporting user feedback across multiple applications
  version: 1.1.0

servers:
  - url: /api
    description: API Gateway via CloudFront

paths:
  /{appId}/responses:
    post:
      summary: Submit feedback response
      description: |
        Submits a feedback response for the specified app.
        All fields in the request body are optional.
        An empty body is valid (submits a blank response).
        The backend does not validate appId or field values — any values are accepted and stored as-is.
        App validation is handled by the frontend before submission.
      operationId: submitResponse
      parameters:
        - name: appId
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9-]+$"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitResponseBody"
            examples:
              fullResponse:
                summary: All fields filled
                value:
                  name: "山田太郎"
                  rating: 2
                  comment: "使いやすかった"
              emptyResponse:
                summary: Empty submission
                value: {}
              partialResponse:
                summary: Only rating
                value:
                  rating: 3
      responses:
        "201":
          description: Response submitted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitResponseResult"
              example:
                responseId: "01HGW2XYZ123ABC"
                submittedAt: "2026-01-28T10:30:00.000Z"

  /responses/csv:
    get:
      summary: Download responses as CSV with optional date filter
      description: |
        Returns feedback responses as a CSV file, optionally filtered by date range.
        The CSV uses UTF-8 encoding with BOM for Excel compatibility.
        Columns include all fields that exist in any response.
        Missing fields in older responses appear as empty cells.
        No authentication required (MVP).

        **Date Range Filtering**:
        - `from`: Include responses from this date (JST 00:00:00.000)
        - `to`: Include responses up to this date (JST 23:59:59.999)
        - Both parameters are optional and can be used independently
        - If neither is specified, all responses are returned (backward compatible)

        **Date Format**: YYYY-MM-DD (e.g., 2026-01-15)
      operationId: downloadCsv
      parameters:
        - name: from
          in: query
          required: false
          description: Start date (inclusive) in YYYY-MM-DD format, interpreted as JST
          schema:
            type: string
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          example: "2026-01-01"
        - name: to
          in: query
          required: false
          description: End date (inclusive) in YYYY-MM-DD format, interpreted as JST
          schema:
            type: string
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          example: "2026-01-31"
      responses:
        "200":
          description: CSV file download
          headers:
            Content-Disposition:
              schema:
                type: string
              example: 'attachment; filename="feedback.csv"'
          content:
            text/csv:
              schema:
                type: string
                format: binary
              example: |
                responseId,appId,submittedAt,comment,name,rating
                01HGW2XYZ123ABC,app1,2026-01-28T10:30:00.000Z,使いやすかった,山田太郎,2
        "204":
          description: No responses match the filter criteria or no data exists
        "400":
          description: Invalid date parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DateValidationError"

components:
  schemas:
    SubmitResponseBody:
      type: object
      description: |
        Feedback response fields. All properties are optional.
        Additional properties are accepted for schema evolution.
      properties:
        name:
          type: string
          description: Respondent name
          example: "山田太郎"
        rating:
          type: number
          description: Rating value (UI guides 1-3, but any value accepted)
          example: 2
        comment:
          type: string
          description: Free-text comment
          example: "使いやすかった"
      additionalProperties: true

    SubmitResponseResult:
      type: object
      required:
        - responseId
        - submittedAt
      properties:
        responseId:
          type: string
          description: Generated unique response ID (ULID)
          example: "01HGW2XYZ123ABC"
        submittedAt:
          type: string
          format: date-time
          description: Server-generated submission timestamp (ISO 8601 UTC)
          example: "2026-01-28T10:30:00.000Z"

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error description
          example: "App not found"

    DateValidationError:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          enum:
            - INVALID_DATE_FORMAT
            - INVALID_DATE
          description: Error code for programmatic handling
        message:
          type: string
          description: Human-readable error description
          example: "from パラメータは YYYY-MM-DD 形式で指定してください"
